yes | ../sbin/remove_all_projects 

yes | ../sbin/remove_runtable DummyRunTable01
yes | ../sbin/remove_runtable DummyRunTable02
yes | ../sbin/remove_runtable DummyRunTable03
yes | ../sbin/remove_runtable DummyRunTable04
yes | ../sbin/remove_runtable DummyRunTable05
yes | ../sbin/remove_runtable DummyRunTable06
yes | ../sbin/remove_runtable DummyRunTable07
yes | ../sbin/remove_runtable DummyRunTable08
yes | ../sbin/remove_runtable DummyRunTable09
yes | ../sbin/remove_runtable DummyRunTable10
yes | ../sbin/remove_runtable DummyRunTable11
yes | ../sbin/remove_runtable FragmentRunTable_seb01
yes | ../sbin/remove_runtable FragmentRunTable_seb02
yes | ../sbin/remove_runtable FragmentRunTable_seb03
yes | ../sbin/remove_runtable FragmentRunTable_seb04
yes | ../sbin/remove_runtable FragmentRunTable_seb05
yes | ../sbin/remove_runtable FragmentRunTable_seb06
yes | ../sbin/remove_runtable FragmentRunTable_seb07
yes | ../sbin/remove_runtable FragmentRunTable_seb08
yes | ../sbin/remove_runtable FragmentRunTable_seb09
yes | ../sbin/remove_runtable FragmentRunTable_seb10
yes | ../sbin/remove_runtable LockedRunTable_seb01
yes | ../sbin/remove_runtable LockedRunTable_seb02
yes | ../sbin/remove_runtable LockedRunTable_seb03
yes | ../sbin/remove_runtable LockedRunTable_seb04
yes | ../sbin/remove_runtable LockedRunTable_seb05
yes | ../sbin/remove_runtable LockedRunTable_seb06
yes | ../sbin/remove_runtable LockedRunTable_seb07
yes | ../sbin/remove_runtable LockedRunTable_seb08
yes | ../sbin/remove_runtable LockedRunTable_seb09
yes | ../sbin/remove_runtable LockedRunTable_seb10

yes | ../sbin/create_runtable DummyRunTable01
yes | ../sbin/create_runtable DummyRunTable02
yes | ../sbin/create_runtable DummyRunTable03
yes | ../sbin/create_runtable DummyRunTable04
yes | ../sbin/create_runtable DummyRunTable05
yes | ../sbin/create_runtable DummyRunTable06
yes | ../sbin/create_runtable DummyRunTable07
yes | ../sbin/create_runtable DummyRunTable08
yes | ../sbin/create_runtable DummyRunTable09
yes | ../sbin/create_runtable DummyRunTable10
yes | ../sbin/create_runtable DummyRunTable11
yes | ../sbin/create_runtable FragmentRunTable_seb01
yes | ../sbin/create_runtable FragmentRunTable_seb02
yes | ../sbin/create_runtable FragmentRunTable_seb03
yes | ../sbin/create_runtable FragmentRunTable_seb04
yes | ../sbin/create_runtable FragmentRunTable_seb05
yes | ../sbin/create_runtable FragmentRunTable_seb06
yes | ../sbin/create_runtable FragmentRunTable_seb07
yes | ../sbin/create_runtable FragmentRunTable_seb08
yes | ../sbin/create_runtable FragmentRunTable_seb09
yes | ../sbin/create_runtable FragmentRunTable_seb10
yes | ../sbin/create_runtable LockedRunTable_seb01
yes | ../sbin/create_runtable LockedRunTable_seb02
yes | ../sbin/create_runtable LockedRunTable_seb03
yes | ../sbin/create_runtable LockedRunTable_seb04
yes | ../sbin/create_runtable LockedRunTable_seb05
yes | ../sbin/create_runtable LockedRunTable_seb06
yes | ../sbin/create_runtable LockedRunTable_seb07
yes | ../sbin/create_runtable LockedRunTable_seb08
yes | ../sbin/create_runtable LockedRunTable_seb09
yes | ../sbin/create_runtable LockedRunTable_seb10

python generate_register_snova.py

yes | ../sbin/register_project register_snova.cfg
yes | ../sbin/register_daemon ../daemon.cfg
