
#
# Some fixed status values for online processing
# 
kSTATUS_DONE            = 0
kSTATUS_INIT            = 1
kSTATUS_TO_BE_VALIDATED = 2
kSTATUS_POSTPONE        = 1000
kSTATUS_TO_BE_SWIZZLED  = 1001

kSTATUS_ERROR_UNKNOWN = 100

kSTATUS_ERROR_REFERENCE_PROJECT_DATA = 109

kSTATUS_ERROR_DUPLICATE_SAM_ENTRY   = 110
kSTATUS_ERROR_WRONG_JSON_FORMAT     = 111
kSTATUS_ERROR_CANNOT_MAKE_SAM_ENTRY = 112

kSTATUS_ERROR_CANNOT_MAKE_BIN_METADATA   = 120
kSTATUS_ERROR_CANNOT_UPLOAD_BIN_METADATA = 121

kSTATUS_ERROR_CHECKSUM_MISMATCH  = 130
kSTATUS_ERROR_CHECKSUM_NOT_FOUND = 131

kSTATUS_ERROR_CANNOT_REMOVE_FILE = 140

kSTATUS_ERROR_INPUT_FILE_NOT_FOUND   = 404
kSTATUS_ERROR_INPUT_FILE_NOT_UNIQUE  = 405
kSTATUS_ERROR_OUTPUT_FILE_NOT_FOUND  = 406
kSTATUS_ERROR_OUTPUT_FILE_NOT_UNIQUE = 407

#
# Metadata types
#
kUBDAQ_METADATA, kSWIZZLED_METADATA, kMAXTYPE_METADATA = xrange(3)
